
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed May 03 14:22:21 CEST 2023
//----------------------------------------------------

package implementacion.c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SEQ = 39;
  public static final int DIVIDE = 5;
  public static final int DOSPUNTOS = 22;
  public static final int CCIERRE = 18;
  public static final int CIRCUNFLEJO = 20;
  public static final int PCIERRE = 14;
  public static final int RESTA = 3;
  public static final int BNE = 12;
  public static final int CAPERTURA = 17;
  public static final int INT = 23;
  public static final int PUNTOCOMA = 15;
  public static final int ARRAY = 43;
  public static final int WRITE = 48;
  public static final int DELETE = 46;
  public static final int BGT = 8;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int IGUAL = 16;
  public static final int RECORD = 42;
  public static final int MULTIPLICA = 4;
  public static final int TYPE = 51;
  public static final int LENTERO = 53;
  public static final int OR = 28;
  public static final int BOOL = 25;
  public static final int BEGIN = 40;
  public static final int SUMA = 2;
  public static final int IF = 34;
  public static final int ID = 52;
  public static final int BGE = 10;
  public static final int OF = 44;
  public static final int EOF = 0;
  public static final int TRUE = 31;
  public static final int NEW = 45;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int MODULO = 6;
  public static final int NULL = 30;
  public static final int REAL = 24;
  public static final int BLT = 7;
  public static final int ELSE = 36;
  public static final int PUNTO = 19;
  public static final int PAPERTURA = 13;
  public static final int NL = 49;
  public static final int READ = 47;
  public static final int LCADENA = 55;
  public static final int WHILE = 37;
  public static final int THEN = 35;
  public static final int BLE = 9;
  public static final int END = 41;
  public static final int LREAL = 54;
  public static final int PROC = 33;
  public static final int STRING = 26;
  public static final int FALSE = 32;
  public static final int VAR = 50;
  public static final int DO = 38;
  public static final int BEQ = 11;
}

