/* Generated By:JavaCC: Do not edit this line. ConstructorASTDConstants.java */
package implementacion.c_ast_descendente;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConstructorASTDConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 1;
  /** RegularExpression Id. */
  int Dig = 2;
  /** RegularExpression Id. */
  int DigPos = 3;
  /** RegularExpression Id. */
  int PEntera = 4;
  /** RegularExpression Id. */
  int PDecimal = 5;
  /** RegularExpression Id. */
  int PExp = 6;
  /** RegularExpression Id. */
  int Suma = 9;
  /** RegularExpression Id. */
  int Resta = 10;
  /** RegularExpression Id. */
  int Multiplica = 11;
  /** RegularExpression Id. */
  int Divide = 12;
  /** RegularExpression Id. */
  int Modulo = 13;
  /** RegularExpression Id. */
  int BLT = 14;
  /** RegularExpression Id. */
  int BGT = 15;
  /** RegularExpression Id. */
  int BLE = 16;
  /** RegularExpression Id. */
  int BGE = 17;
  /** RegularExpression Id. */
  int BEQ = 18;
  /** RegularExpression Id. */
  int BNE = 19;
  /** RegularExpression Id. */
  int PApertura = 20;
  /** RegularExpression Id. */
  int PCierre = 21;
  /** RegularExpression Id. */
  int PuntoComa = 22;
  /** RegularExpression Id. */
  int Igual = 23;
  /** RegularExpression Id. */
  int CApertura = 24;
  /** RegularExpression Id. */
  int CCierre = 25;
  /** RegularExpression Id. */
  int Punto = 26;
  /** RegularExpression Id. */
  int Circunflejo = 27;
  /** RegularExpression Id. */
  int Coma = 28;
  /** RegularExpression Id. */
  int DosPuntos = 29;
  /** RegularExpression Id. */
  int Int = 30;
  /** RegularExpression Id. */
  int Real = 31;
  /** RegularExpression Id. */
  int Bool = 32;
  /** RegularExpression Id. */
  int String = 33;
  /** RegularExpression Id. */
  int And = 34;
  /** RegularExpression Id. */
  int Or = 35;
  /** RegularExpression Id. */
  int Not = 36;
  /** RegularExpression Id. */
  int Null = 37;
  /** RegularExpression Id. */
  int True = 38;
  /** RegularExpression Id. */
  int False = 39;
  /** RegularExpression Id. */
  int Proc = 40;
  /** RegularExpression Id. */
  int If = 41;
  /** RegularExpression Id. */
  int Then = 42;
  /** RegularExpression Id. */
  int Else = 43;
  /** RegularExpression Id. */
  int While = 44;
  /** RegularExpression Id. */
  int Do = 45;
  /** RegularExpression Id. */
  int Seq = 46;
  /** RegularExpression Id. */
  int Begin = 47;
  /** RegularExpression Id. */
  int End = 48;
  /** RegularExpression Id. */
  int Record = 49;
  /** RegularExpression Id. */
  int Array = 50;
  /** RegularExpression Id. */
  int Of = 51;
  /** RegularExpression Id. */
  int New = 52;
  /** RegularExpression Id. */
  int Delete = 53;
  /** RegularExpression Id. */
  int Read = 54;
  /** RegularExpression Id. */
  int Write = 55;
  /** RegularExpression Id. */
  int Nl = 56;
  /** RegularExpression Id. */
  int Var = 57;
  /** RegularExpression Id. */
  int Type = 58;
  /** RegularExpression Id. */
  int Id = 59;
  /** RegularExpression Id. */
  int LEntero = 60;
  /** RegularExpression Id. */
  int LReal = 61;
  /** RegularExpression Id. */
  int LCadena = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letra>",
    "<Dig>",
    "<DigPos>",
    "<PEntera>",
    "<PDecimal>",
    "<PExp>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"^\"",
    "\",\"",
    "\":\"",
    "<Int>",
    "<Real>",
    "<Bool>",
    "<String>",
    "<And>",
    "<Or>",
    "<Not>",
    "<Null>",
    "<True>",
    "<False>",
    "<Proc>",
    "<If>",
    "<Then>",
    "<Else>",
    "<While>",
    "<Do>",
    "<Seq>",
    "<Begin>",
    "<End>",
    "<Record>",
    "<Array>",
    "<Of>",
    "<New>",
    "<Delete>",
    "<Read>",
    "<Write>",
    "<Nl>",
    "<Var>",
    "<Type>",
    "<Id>",
    "<LEntero>",
    "<LReal>",
    "<LCadena>",
  };

}
